apiVersion: v1
kind: Service
metadata:
  name: homestaygripzzy-service
spec:
  selector:
    app: homestaygripzzy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
